### ISSUE TITLE
我想请问一下,你的这个githubio是用的hexo模板吗

### ISSUE THREAD

**Issue by 2662419405** [miluluyo/miluluyo.github.io#1]
我想请问一下,你的这个githubio是用的hexo模板吗,还是说自己手写的html呢,想请教一下,谢谢

**Comment by miluluyo** [comment]
不好意思哈~现在才看到~这个用的是vuepress~

**Comment by 2662419405** [comment]
好的,感谢分享
感觉你的这个页面刷新起来好快啊 学习一波
